

/*=========================================================
  Magnitude_analysis
  
=========================================================*/

-- =====================================================
-- 1. Find Total Customers by Country
-- =====================================================

SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;


-- =====================================================
-- 2. Find Total Customers by Gender
-- =====================================================

SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;


-- =====================================================
-- 3. Find Total Products by Category
-- =====================================================

SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;


-- =====================================================
-- 4. Find Average Cost in Each Category
-- =====================================================

SELECT
    category,
    AVG(cost) AS avg_costs
FROM gold.dim_products
GROUP BY category
ORDER BY avg_costs DESC;


-- =====================================================
-- 5. Find Total Revenue Generated for Each Category
-- =====================================================

SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


-- =====================================================
-- 6. Find Total Revenue Generated by Each Customer
-- =====================================================

SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;


-- =====================================================
-- 7. Distribution of Sold Items Across Countries
-- =====================================================

SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;
